"""init schema

Revision ID: 1c3500c62171
Revises: 
Create Date: 2026-01-14 23:12:01.232846

"""
from typing import Sequence, Union
from sqlalchemy.dialects.postgresql import TSVECTOR
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '1c3500c62171'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('type', 'name', name='uq_sources_type_name')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=True)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column("tsv", TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_document_index')
    )
    op.execute("""
        UPDATE chunks
        SET tsv = to_tsvector('russian', content)
    """)

    op.create_index(
        "ix_chunks_tsv",
        "chunks",
        ["tsv"],
        postgresql_using="gin",
    )

    op.execute("""
    CREATE FUNCTION chunks_tsv_trigger() RETURNS trigger AS $$
    begin
      new.tsv := to_tsvector('russian', new.content);
      return new;
    end
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER chunks_tsv_update
    BEFORE INSERT OR UPDATE
    ON chunks
    FOR EACH ROW EXECUTE FUNCTION chunks_tsv_trigger();
    """)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_embeddings_chunk_id_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('chunk_id', 'model_name', name='uq_embeddings_chunk_model')
    )
    # op.create_index(op.f('ix_embeddings_model_name'), 'embeddings', ['model_name'], unique=False)
    op.create_index(
    "ix_embeddings_embedding_hnsw",
    "embeddings",
    ["embedding"],
    postgresql_using="hnsw",
    postgresql_ops={
        "embedding": "vector_cosine_ops",
    },
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_embeddings_model_name'), table_name='embeddings')
    
    op.drop_index("ix_embeddings_embedding_hnsw", table_name="embeddings")
    op.drop_table('embeddings')
    op.execute("DROP TRIGGER IF EXISTS chunks_tsv_update ON chunks")
    op.execute("DROP FUNCTION IF EXISTS chunks_tsv_trigger")

    op.drop_index("ix_chunks_tsv", table_name="chunks")
    op.drop_table('chunks')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('sources')
    # ### end Alembic commands ###
